name:                noc
version:             0.2.0.0
github:              "noc-lang/noc"
license:             BSD3
author:              "mortim"
maintainer:          "aouladkarim010@gmail.com"
copyright:           "2022 mortim"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            A user-friendly concatenative language
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:          

dependencies:
- base >= 4.7 && < 5
- parsec
- haskeline
- directory
- optparse-applicative
- containers
- text
- binary
- bytestring
- process

library:
  source-dirs: src

executables:
  noc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - noc

tests:
  noc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - noc