name:                noc
version:             0.1.0.0
github:              "kaoulad/noc-lang/noc"
license:             BSD3
author:              "kaoulad"
maintainer:          "kaoulad@pm.me"
copyright:           "2020 kaoulad"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            User-friendly stack-based concatenative language,
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:          

dependencies:
- base >= 4.7 && < 5
- parsec
- ansi-terminal
- optparse-applicative
- mtl
- containers

library:
  source-dirs: src

executables:
  noc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - noc

tests:
  noc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - noc
    - QuickCheck
    - hspec
