name:                noc
version:             0.1.0.0
github:              "mortim1/noc"
license:             BSD3
author:              "mortim"
maintainer:          "mortim1@protonmail.com"
copyright:           "2020 mortim"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:          Concatenative language made to learning more about PLT. 

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  noc-language:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - noc

tests:
  noc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - noc
